// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWHnVkq4-pfkvrWo82IlfY1cKSrD5fT_I',
    appId: '1:259941404916:web:04f2102a6ad532d0314ea1',
    messagingSenderId: '259941404916',
    projectId: 'todoapp-a5823',
    authDomain: 'todoapp-a5823.firebaseapp.com',
    storageBucket: 'todoapp-a5823.appspot.com',
    measurementId: 'G-FJK6NQGEG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHKVyri3r2v2i6JpEEZZKNRLEmTJ__AZE',
    appId: '1:259941404916:android:100f07eeb93afa2e314ea1',
    messagingSenderId: '259941404916',
    projectId: 'todoapp-a5823',
    storageBucket: 'todoapp-a5823.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnV-ekmzG6SuYieXzSFm3p9xLOr7ZjttE',
    appId: '1:259941404916:ios:d3722348962307ab314ea1',
    messagingSenderId: '259941404916',
    projectId: 'todoapp-a5823',
    storageBucket: 'todoapp-a5823.appspot.com',
    androidClientId:
        '259941404916-1po2nvq02kr6q508ej4oomua4325gqm5.apps.googleusercontent.com',
    iosClientId:
        '259941404916-qba52l59j3rrjigalsh18o2578d6stf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppWorkruit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnV-ekmzG6SuYieXzSFm3p9xLOr7ZjttE',
    appId: '1:259941404916:ios:8197dbc077134b4f314ea1',
    messagingSenderId: '259941404916',
    projectId: 'todoapp-a5823',
    storageBucket: 'todoapp-a5823.appspot.com',
    androidClientId:
        '259941404916-1po2nvq02kr6q508ej4oomua4325gqm5.apps.googleusercontent.com',
    iosClientId:
        '259941404916-cn0o2e1qistm8pqjfimguc8rfmju8dhb.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoAppWorkruit.RunnerTests',
  );
}
